# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "P. James Joyce"
description: > # this means to ignore newlines until "email:"
   LCA practitioner, PhD researcher, Sustainability Consultant

email: pjamesjoyce@gmail.com
#blog logo
logo: "/notebooks/assets/images/pjj_logo.jpg"
# blog cover
cover: "/notebooks/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'James Joyce'
author: 'James Joyce'
author_image: "/notebooks/assets/images/pjj_logo.jpg"

paginate:	5

url: "https://pjamesjoyce.github.io/notebooks/" # the base hostname & protocol for your site
baseurl: "https://pjamesjoyce.github.io/notebooks/"
#used to display twitter cards
twitter_handle: '@KTH_James'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/KTH_James
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/redmudproject
    desc: Connect with me facebook
    share_url: https://www.facebook.com/sharer.php
    share_title: ?t=
    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/pjamesjoyce
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
